version: "3.8"
services:
  sbbs:
    container_name: sbbs
    build:
      context: .
    deploy:
      restart_policy:
        condition: any
        delay: 3s
    volumes:
      - ~/sbbs/ctrl:/sbbs/ctrl
      - ~/sbbs/text:/sbbs/text
      - ~/sbbs/web:/sbbs/web
      - ~/sbbs/data:/sbbs/data
      - ~/sbbs/fido:/sbbs/fido
      - ~/sbbs/xtrn:/sbbs/xtrn
      - ~/sbbs/mods:/sbbs/mods
      - ~/sbbs/nodes:/sbbs/nodes
      - ~/sbbs/backup:/backup
    networks:
      - sbbs
    ports:
      - 80:80 #http
      - 443:443 #https
      - 1123:1123 #ws-term
      - 11235:11235 #wss-term
      - "21:21" #ftp
      - "22:22" #ssh
      - "23:23" #telnet
      - "513:513" #rlogin
      - "64:64" #petscii 40-column
      - "128:128" #petscii 128-column
      - "25:25" #smtp-mail
      - 587:587 #smtp-submit
      - 465:465 #smtp-submit+tls
      - 110:110 #pop3
      - 995:995 #pop3+tls
      - 119:119 #nntp
      - 563:563 #nntps
      - "18:18" #message send prot
      - "11:11" #active user svc
      - "17:17" #qotd
      - 79:79 #finger
      - 6667:6667 #irc
      # - 5500:5500 #hotline
      # - 5501:5501 #hotline-trans
      # - 24554:24554 #binkp
      # - 24553:24553 #binkps
      # - 143:143 #imap
      # - 993:993 #imap+tls
  # sbbs_irc:
  #   container_name: sbbs_irc
  #   build:
  #     context: .
  #   deploy:
  #     restart_policy:
  #       condition: any
  #       delay: 3s
  #   volumes:
  #     - ~/sbbs/ctrl:/sbbs/ctrl
  #     - ~/sbbs/text:/sbbs/text
  #     - ~/sbbs/data:/sbbs/data
  #     - ~/sbbs/mods:/sbbs/mods
  #   command: jsexec /sbbs/exec/ircd.js
  #   ports:
  #     - 6667:6667
  # sbbs_ecweb:
  #   container_name: sbbs_ecweb
  #   build:
  #     context: .
  #   deploy:
  #     restart_policy:
  #       condition: any
  #       delay: 3s
  #   volumes:
  #     - ~/sbbs/ctrl:/sbbs/ctrl
  #     - ~/sbbs/text:/sbbs/text
  #     - ~/sbbs/data:/sbbs/data
  #     - ~/sbbs/mods:/sbbs/mods
  #     - ~/sbbs/web-ecweb4:/sbbs/web
  #   command: bash -c "sleep 10 && /sbbs/exec/sbbs t- f- m- s- ~/sbbs/ctrl/sbbs.web-ecweb4.ini"
  #   ports:
  #     - 51080:80
  #     - 51443:443
  # sbbs_rmweb:
  #   container_name: sbbs_rmweb
  #   build:
  #     context: .
  #   deploy:
  #     restart_policy:
  #       condition: any
  #       delay: 3s
  #   volumes:
  #     - ~/sbbs/ctrl:/sbbs/ctrl
  #     - ~/sbbs/text:/sbbs/text
  #     - ~/sbbs/data:/sbbs/data
  #     - ~/sbbs/mods:/sbbs/mods
  #     - ~/sbbs/web-runemaster:/sbbs/web
  #   command: bash -c "sleep 10 && /sbbs/exec/sbbs t- f- m- s- ~/sbbs/ctrl/sbbs.web-runemaster.ini"
  #   ports:
  #     - 52080:80
  #     - 52443:443

networks:
  sbbs:
