# Advanced example of a docker-compose file...
# This assumes you have irc disabled in services.ini, so you can run it as a
# separate container and additional directories for the web instances

#  - ~/sbbs/web-ecweb4      copy from ~/sbbs/backup/default/
#  - ~/sbbs/web-runemaster  copy from ~/sbbs/backup/default/
version: "3.8"
services:
  sbbs:
    container_name: sbbs
    image: bbsio/synchronet:nightly
    deploy:
      restart_policy:
        condition: any
    volumes:
      - $PWD/ctrl:/sbbs/ctrl
      - $PWD/nodes:/sbbs/nodes
      - $PWD/text:/sbbs/text
      - $PWD/web:/sbbs/web
      - $PWD/data:/sbbs/data
      - $PWD/fido:/sbbs/fido
      - $PWD/xtrn:/sbbs/xtrn
      - $PWD/mods:/sbbs/mods
      - $PWD/backup:/backup
    networks:
      - bbs
    ports:
      - 80:80 #http
      - 443:443 #https
      - 1123:1123 #ws-term
      - 11235:11235 #wss-term
      - "21:21" #ftp
      - "22:22" #ssh
      - "23:23" #telnet
      - "513:513" #rlogin
      - "64:64" #petscii 40-column
      - "128:128" #petscii 128-column
      - "25:25" #smtp-mail
      - 587:587 #smtp-submit
      - 465:465 #smtp-submit+tls
      - 110:110 #pop3
      - 995:995 #pop3+tls
      - 119:119 #nntp
      - 563:563 #nntps
      - "18:18" #message send prot
      - "11:11" #active user svc
      - "17:17" #qotd
      - 79:79 #finger
      # - 6667:6667 #irc
      # - 5500:5500 #hotline
      # - 5501:5501 #hotline-trans
      # - 24554:24554 #binkp
      # - 24553:24553 #binkps
      # - 143:143 #imap
      # - 993:993 #imap+tls
  sbbs_irc:
    container_name: sbbs_irc
    image: bbsio/synchronet:nightly
    deploy:
      restart_policy:
        condition: any
    volumes:
      - $PWD/ctrl:/sbbs/ctrl
      - $PWD/nodes:/sbbs/nodes
      - $PWD/text:/sbbs/text
      - $PWD/data:/sbbs/data
      - $PWD/mods:/sbbs/mods
    command: bash -c "echo 'starting in 10 seconds' && sleep 10 && sbbs-init && jsexec -L9 /sbbs/exec/ircd.js"
    ports:
      - 6667:6667

  sbbs_ecweb:
    container_name: sbbs_ecweb
    image: bbsio/synchronet:nightly
    deploy:
      restart_policy:
        condition: any
    volumes:
      - $PWD/ctrl:/sbbs/ctrl
      - $PWD/nodes:/sbbs/nodes
      - $PWD/text:/sbbs/text
      - $PWD/data:/sbbs/data
      - $PWD/mods:/sbbs/mods
      - $PWD/web-ecweb4:/sbbs/web
    command: bash -c "echo 'starting in 10 seconds' && sleep 10 && sbbs-init && /sbbs/exec/sbbs t- f- m- s-"
    ports:
      - 51080:80

  sbbs_rmweb:
    image: bbsio/synchronet:nightly
    deploy:
      restart_policy:
        condition: any
    volumes:
      - $PWD/ctrl:/sbbs/ctrl
      - $PWD/nodes:/sbbs/nodes
      - $PWD/text:/sbbs/text
      - $PWD/data:/sbbs/data
      - $PWD/mods:/sbbs/mods
      - $PWD/web-runemaster:/sbbs/web
    command: bash -c "echo 'starting in 10 seconds' && sleep 10 && sbbs-init && /sbbs/exec/sbbs t- f- m- s-"
    ports:
      - 52080:80
  doorparty:
    hostname: doorparty
    container_name: doorparty
    image: bbsio/doorparty:latest
    environment:
      - SSH_USERNAME=foo
      - SSH_PASSWORD=bar
      - SYSTEM_TAG=[FOO]
    deploy:
      restart_policy:
        condition: any
    networks:
      - bbs
networks:
  bbs:
