#!/bin/bash

mkdir -p ~/sbbs
cd ~/sbbs

# Create sbbs network if it doesn't exist
(docker network create -d bridge sbbs > /dev/null 2>&1 || echo '')
echo 'Docker network "sbbs" ready'

docker run -d \
  --name sbbs \
  --network sbbs \
  --restart unless-stopped \
  -v $(pwd)/ctrl:/sbbs/ctrl \
  -v $(pwd)/text:/sbbs/text \
  -v $(pwd)/web:/sbbs/web \
  -v $(pwd)/data:/sbbs/data \
  -v $(pwd)/fido:/sbbs/fido \
  -v $(pwd)/xtrn:/sbbs/xtrn \
  -v $(pwd)/mods:/sbbs/mods \
  -v $(pwd)/nodes:/sbbs/nodes \
  -v $(pwd)/backup:/backup \
  $@ \
  sbbs

echo 'Docker container "sbbs" started.'
