#!/bin/bash

mkdir -p ~/sbbs
cd ~/sbbs

# Create sbbs network if it doesn't exist
(docker network create -d bridge sbbs > /dev/null 2>&1 || echo '')

docker run --rm -it \
  --name sbbs \
  --network sbbs \
  -v $(pwd)/ctrl:/sbbs/ctrl \
  -v $(pwd)/text:/sbbs/text \
  -v $(pwd)/web:/sbbs/web \
  -v $(pwd)/data:/sbbs/data \
  -v $(pwd)/fido:/sbbs/fido \
  -v $(pwd)/xtrn:/sbbs/xtrn \
  -v $(pwd)/mods:/sbbs/mods \
  -v $(pwd)/reference:/sbbs/reference \
  sbbs \
  $@
