#! /bin/sh

SCRIPTSDIR="$(dirname -- "$0")"

# /sbbs/data setup first
mkdir -p /sbbs-data/.deno/gen
mkdir -p /sbbs-data/.deno/deps
mkdir -p /sbbs-data/.deno/bin
mkdir -p /sbbs-data/data
[ ! -d "/sbbs/data" ] && sudo ln -s /sbbs-data/data /sbbs

# Run initialization
sudo deno -q run \
  --import-map $SCRIPTSDIR/vendor/import_map.json \
  --unstable --allow-run --allow-read --allow-write \
  $SCRIPTSDIR/init.ts || exit $?

# correct ownership and permissions after general initialization
UID=$(id -u)
GID=$(id -g)
sudo chown -R $UID:$GID /sbbs-data || exit $?
sudo chmod -R a+rwX /sbbs-data || exit $?
