# This will by copied to ~/sbbs/docker-compose.yml
#
# It will be used in order to customize the running
# and installation options.
#
# In order to customize before first install
# run:
#    sbbs init
version: "3.8"
services:
  sbbs:
    container_name: sbbs

    # -- LATEST PREBUILT ------------------------
    image: bbsio/synchronet:latest
    # -------------------------------------------

    # -- NIGHTLY --------------------------------
    # Nightly images are tagged with
    # year-month-day as follows.
    #
    # image: bbsio/synchronet:nightly-YYYYMMDD
    # image: bbsio/synchronet:nightly-20210218
    # -------------------------------------------

    deploy:
      restart_policy:
        condition: any
    volumes:
      - ~/sbbs/ctrl:/sbbs/ctrl
      - ~/sbbs/text:/sbbs/text
      - ~/sbbs/web:/sbbs/web
      - ~/sbbs/data:/sbbs/data
      - ~/sbbs/fido:/sbbs/fido
      - ~/sbbs/xtrn:/sbbs/xtrn
      - ~/sbbs/mods:/sbbs/mods
      - ~/sbbs/nodes:/sbbs/nodes
      - ~/sbbs/backup:/backup
    networks:
      - sbbs
    ports:
      - 80:80 #http
      - 443:443 #https
      - 1123:1123 #ws-term
      - 11235:11235 #wss-term
      - "21:21" #ftp
      - "22:22" #ssh
      - "23:23" #telnet
      - "513:513" #rlogin
      - "64:64" #petscii 40-column
      - "128:128" #petscii 128-column
      - "25:25" #smtp-mail
      - 587:587 #smtp-submit
      - 465:465 #smtp-submit+tls
      - 110:110 #pop3
      - 995:995 #pop3+tls
      - 119:119 #nntp
      - 563:563 #nntps
      - "18:18" #message send prot
      - "11:11" #active user svc
      - "17:17" #qotd
      - 79:79 #finger
      - 6667:6667 #irc
      # - 5500:5500 #hotline
      # - 5501:5501 #hotline-trans
      # - 24554:24554 #binkp
      # - 24553:24553 #binkps
      # - 143:143 #imap
      # - 993:993 #imap+tls
networks:
  sbbs:
    name: sbbs
