#!/bin/bash

cd -P -- "$(dirname -- "$0")/"

mkdir -p ~/sbbs/ctrl
mkdir -p ~/sbbs/text
mkdir -p ~/sbbs/web
mkdir -p ~/sbbs/data
mkdir -p ~/sbbs/fido
mkdir -p ~/sbbs/xtrn
mkdir -p ~/sbbs/mods
mkdir -p ~/sbbs/nodes
mkdir -p ~/sbbs/backup

# Create sbbs network if it doesn't exist
(docker network create -d bridge sbbs > /dev/null 2>&1 || echo '')

run_bash() {
  SBBSDIR="$(dirname ~/sbbs)"

  docker run --rm -t \
    --network sbbs \
    -v $SBBSDIR/ctrl:/sbbs/ctrl \
    -v $SBBSDIR/text:/sbbs/text \
    -v $SBBSDIR/web:/sbbs/web \
    -v $SBBSDIR/data:/sbbs/data \
    -v $SBBSDIR/fido:/sbbs/fido \
    -v $SBBSDIR/xtrn:/sbbs/xtrn \
    -v $SBBSDIR/mods:/sbbs/mods \
    -v $SBBSDIR/nodes:/sbbs/nodes \
    -v $SBBSDIR/backup:/backup \
    node:14-stretch bash -c "$1"
}

run_bash "chmod -R a+rwX /backup \
  && chmod -R a+rwX /sbbs/ctrl \
  && chmod -R a+rwX /sbbs/data \
  && chmod -R a+rwX /sbbs/fido \
  && chmod -R a+rwX /sbbs/xtrn \
  && chmod -R a+rwX /sbbs/mods \
  && chmod -R a+rwX /sbbs/nodes \
  && chmod -R a+rwX /sbbs/text \
  && chmod -R a+rwX /sbbs/web "
