#!/usr/bin/env bash

printf "\n\n=============================================\nBuilding Latest Synchronet BBS from CVS...\n"


printf "\n\nPATH=\$PATH:/sbbs-scripts:/sbbs-base/exec\n\n" >> /root/.bashrc
printf "\n\nSBBSCTRL=/sbbs/ctrl\n" >> /root/.bashrc
printf "\nTERM=dumb\n" >> /root/.bashrc

printf "\n\n---\nUpdating package sources"
rm /etc/apt/sources.list
printf "\ndeb http://httpredir.debian.org/debian jessie main contrib non-free" >> /etc/apt/sources.list
printf "\ndeb-src http://httpredir.debian.org/debian jessie main contrib non-free" >> /etc/apt/sources.list
printf "\ndeb http://httpredir.debian.org/debian jessie-updates main contrib non-free" >> /etc/apt/sources.list
printf "\ndeb-src http://httpredir.debian.org/debian jessie-updates main contrib non-free" >> /etc/apt/sources.list
printf "\ndeb http://security.debian.org/ jessie/updates main contrib non-free" >> /etc/apt/sources.list
printf "\ndeb-src http://security.debian.org/ jessie/updates main contrib non-free" >> /etc/apt/sources.list
apt-get update


printf "\n\n---\nInstalling dependencies\n"
apt-get install -y build-essential cvs zip libnspr4 libnspr4-dev dosemu libncurses5-dev libncursesw5-dev

mkdir /sbbs
cd /sbbs

printf "\n\n---\nDownloading Synchronet Installer Script"
wget 'http://cvs.synchro.net/cgi-bin/viewcvs.cgi/*checkout*/install/GNUmakefile'

printf "Compiling... this will take a while..."
make install SBBSDIR=/sbbs USEDOSEMU=1 
#> ./sbbs-install.log 2> ./sbbs-install-errors.log

printf "\n\nCleanup source files\n\n"
cd /sbbs
rm -Rf src
rm -Rf 3rdp
rm -Rf node2
rm -Rf node3
rm -Rf node4
rm GNUmakefile
find . -name CVS -exec rm -rf {} \; 
printf "\n\nSynchronet BBS source files cleaned up.\n\n"

printf "\n\nCleanup cache files\n\n"
apt-get clean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


printf "\n\n\nPrepping SBBS Base\n\n"
cd /
mv /sbbs /sbbs-base

printf "\n\nSynchronet BBS Build Complete.\n=============================================\n\n"
