#!/bin/bash

mkdir -p ~/sbbs
cd ~/sbbs

mkdir -p ./ctrl
mkdir -p ./text
mkdir -p ./web
mkdir -p ./data
mkdir -p ./fido
mkdir -p ./xtrn
mkdir -p ./mods
mkdir -p ./nodes
mkdir -p ./backup

# Create sbbs network if it doesn't exist
(docker network create -d bridge sbbs > /dev/null 2>&1 || echo '')

docker run --rm -it \
  --network sbbs \
  -v $(pwd)/ctrl:/sbbs/ctrl \
  -v $(pwd)/text:/sbbs/text \
  -v $(pwd)/web:/sbbs/web \
  -v $(pwd)/data:/sbbs/data \
  -v $(pwd)/fido:/sbbs/fido \
  -v $(pwd)/xtrn:/sbbs/xtrn \
  -v $(pwd)/mods:/sbbs/mods \
  -v $(pwd)/nodes:/sbbs/nodes \
  -v $(pwd)/backup:/backup \
  bbsio/synchronet:local \
  sbbs-run \
  "$@"
