name: Publish Release
on:
  push:
    tags:
      - "release*"
      - "nightly*"
jobs:
  publish:
    name: Publishing Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Set Docker and SBBS Tags
        id: tags
        run: |
          cd checker
          npm ci
          echo "GITHUB_REF=$GITHUB_REF"
          node -r esm ./get-publish-tags
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Build and Push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          context: ./docker
          push: true
          tags: ${{ steps.tags.outputs.docker_tags }}
          build-args: |
            TAGNAME=${{ steps.tags.outputs.sbbs_tagname }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
