name: Publish Release
on:
  push:
    tags:
      - "release*"
      - "nightly*"
jobs:
  publish:
    name: Publishing Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Set Docker and SBBS Tags
        id: tags
        run: |
          docker pull debian:bullseye-slim
          echo "GITHUB_REF=$GITHUB_REF"
          ./.github/scripts/load-publish-tags.ts || exit 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: ${{ steps.tags.outputs.docker_tags }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Build and Push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        if: ${{ steps.tags.outputs.docker_tags }}
        with:
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          platforms: linux/amd64
          context: ./docker
          push: true
          tags: ${{ steps.tags.outputs.docker_tags }}
          build-args: |
            TAGNAME=${{ steps.tags.outputs.sbbs_tagname }}
      - name: Image digest
        if: ${{ steps.tags.outputs.docker_tags }}
        run: echo ${{ steps.docker_build.outputs.digest }}
